import logoImg from '../assets/svg/logo.svg';
import menuImage from '../assets/svg/coffee-cup.svg';

export const header = document.createElement('header');
header.classList.add('header');
const logo = document.createElement('a');
logo.classList.add('logo');
const logoImage = document.createElement('img');
logoImage.classList.add('logo-image');
logoImage.src = logoImg;
const nav = document.createElement('nav');
nav.classList.add('nav');
const list = document.createElement('ul');
list.classList.add('list');
const listItem1 = document.createElement('li');
listItem1.classList.add('list-item');
const itemLink1 = document.createElement('a');
itemLink1.classList.add('item-link'); 
itemLink1.textContent = 'Favorite coffee';
const listItem2 = document.createElement('li');
listItem2.classList.add('list-item');
const itemLink2 = document.createElement('a');
itemLink2.classList.add('item-link');
itemLink2.textContent = 'About';
const listItem3 = document.createElement('li');
listItem3.classList.add('list-item');
const itemLink3 = document.createElement('a');
itemLink3.classList.add('item-link');
itemLink3.textContent = 'Mobile app'; 
const listItem4 = document.createElement('li');
listItem4.classList.add('list-item');
const itemLink4 = document.createElement('a');
itemLink4.classList.add('item-link'); 
itemLink4.textContent = 'Contact us';
const menu = document.createElement('a');
menu.classList.add('menu');
const menuText = document.createTextNode('Menu');
const menuImg = document.createElement('img');
menuImg.classList.add('menu__image');
menuImg.src = menuImage;


logo.append(logoImage);
nav.append(list);
listItem1.append(itemLink1);
listItem2.append(itemLink2);
listItem3.append(itemLink3);
listItem4.append(itemLink4);
list.append(listItem1, listItem2, listItem3, listItem4);
menu.append(menuText);
menu.append(menuImg);
header.append(logo, nav, menu);