export const heroSection = document.createElement('section');
heroSection.classList.add('section', 'hero-section');
const heroVideoAutoPlay = document.createElement('video');
heroVideoAutoPlay.classList.add('hero-video');
heroVideoAutoPlay.autoplay = true;
heroVideoAutoPlay.loop = true;
heroVideoAutoPlay.muted = true;
heroVideoAutoPlay.controls = false;
heroVideoAutoPlay.controlslist = 'nodownload';
heroVideoAutoPlay.poster = '../assets/img/img-hero.webp';
const videoSource = document.createElement('source');
videoSource.src = './assets/videos/video-2160p.webm';
videoSource.type = 'video/webm';
const heroContent = document.createElement('div');
heroContent.classList.add('hero-block');
const heroTitle = document.createElement('h1');
heroTitle.classList.add('hero-title');
heroTitle.innerHTML = `<span class="italic-accent">Enjoy</span> premium coffee at our charming cafe`
const heroSubtitle = document.createElement('p');
heroSubtitle.textContent = 'With its inviting atmosphere and delicious coffee options, the Coffee House Resource is a popular destination for coffee lovers and those seeking a warm and inviting space to enjoy their favorite beverage.';
heroSubtitle.classList.add('hero-text');
const heroButton = document.createElement('a');
heroButton.classList.add('hero-btn', 'cursor-pointer');
heroButton.href = './menu.html';
heroButton.innerHTML = '<span>Menu</span>';

heroContent.append(heroTitle, heroSubtitle, heroButton);
heroVideoAutoPlay.append(videoSource);
heroSection.append(heroVideoAutoPlay);
heroSection.append(heroContent);